title: Dunkan Boyce # your name (or website title) here
logo: "/images/my_pic2.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | IT Profesional
  <br><br>
  Tech enthusiast 
  <br><br>
  Feel free to look around and connect on Linkedin!  <br><br>
  <a href="https://www.linkedin.com/in/dunkanboyce/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics:
