title: Dunkan Boyce # your name (or website title) here
logo: "/images/my_pic2.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | IT Proffesional | Tech enthusiast 
  <br><br>
  Feel free to look around and connect on Linkedin!  <br><br>
  <a href="https://www.linkedin.com/in/dunkanboyce/">View My LinkedIn Profile</a> 
  
theme: remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics:
